### PR TITLE
CHORE: Brush up on article cards and category bar

### PR DESCRIPTION
**Pull request by LucasKnudsen**
[PT Story](https://www.pivotaltracker.com/story/show/178189683)

### User Story:
```
As a web app
In order to maintain a big-budget appearance
I need occasional brush ups
```

### Screenshot
image

### CODE REVIEW

**Review by lukeperrin10 — APPROVED** [review]

**Review by 1CIM — COMMENTED** [review]
Looking nice! but why not share whole screen pic? how dose the categories, navbar, header look like?

**Comment by LucasKnudsen** [comment]
Screen was too small :(

**Review by tochman — COMMENTED** [review]
There are comments in the code and only 1 peer review

**Review by offcast-dev — APPROVED** [review]
Looks much better

**Pull request merged**
